import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar/Navbar";

import styles from "../styles/Home.module.css";

export default function PageHome() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Paroki Santo Yakobus</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className={styles.header}>
				<Navbar />
			</header>

			<main className={styles.main}>
				<div className={styles.heroWrapper}>
					<Image
						className={styles.heroImage}
						priority
						src={"/static/hero.jpg"}
						alt="Foto Gereja Paroki"
						width={1600}
						height={900}
					/>
					<div className={styles.heroContent}>
						<p className={styles.heroText}>
							<span>PAROKI</span>
							<span>SANTO YAKOBUS</span>
							<span>BANTUL</span>
						</p>
						<div className={styles.heroButtons}>
							<button className={styles.button}>PENGUMUMAN PAROKI</button>
							<button className={styles.button}>JADWAL EKARISTI</button>
						</div>
					</div>
				</div>

				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis,
					numquam quae nostrum ullam voluptatum distinctio maxime eos voluptate
					ea ad quos repudiandae, deserunt non magni magnam pariatur,
					perferendis aut libero incidunt similique aliquam error recusandae
					provident modi. Dolorum, modi. Asperiores vel natus neque accusamus
					iure officia quis amet. Expedita odit maiores debitis explicabo, odio
					est? Ratione necessitatibus laboriosam officia debitis corrupti
					doloremque reprehenderit quisquam quibusdam obcaecati maxime, expedita
					libero facere maiores, magnam alias explicabo quo repudiandae? Quia
					nam maiores recusandae expedita, aperiam fugiat excepturi atque
					commodi inventore fuga officiis, consectetur culpa laboriosam, harum
					mollitia magnam. Distinctio pariatur dolores saepe nesciunt.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis,
					numquam quae nostrum ullam voluptatum distinctio maxime eos voluptate
					ea ad quos repudiandae, deserunt non magni magnam pariatur,
					perferendis aut libero incidunt similique aliquam error recusandae
					provident modi. Dolorum, modi. Asperiores vel natus neque accusamus
					iure officia quis amet. Expedita odit maiores debitis explicabo, odio
					est? Ratione necessitatibus laboriosam officia debitis corrupti
					doloremque reprehenderit quisquam quibusdam obcaecati maxime, expedita
					libero facere maiores, magnam alias explicabo quo repudiandae? Quia
					nam maiores recusandae expedita, aperiam fugiat excepturi atque
					commodi inventore fuga officiis, consectetur culpa laboriosam, harum
					mollitia magnam. Distinctio pariatur dolores saepe nesciunt.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis,
					numquam quae nostrum ullam voluptatum distinctio maxime eos voluptate
					ea ad quos repudiandae, deserunt non magni magnam pariatur,
					perferendis aut libero incidunt similique aliquam error recusandae
					provident modi. Dolorum, modi. Asperiores vel natus neque accusamus
					iure officia quis amet. Expedita odit maiores debitis explicabo, odio
					est? Ratione necessitatibus laboriosam officia debitis corrupti
					doloremque reprehenderit quisquam quibusdam obcaecati maxime, expedita
					libero facere maiores, magnam alias explicabo quo repudiandae? Quia
					nam maiores recusandae expedita, aperiam fugiat excepturi atque
					commodi inventore fuga officiis, consectetur culpa laboriosam, harum
					mollitia magnam. Distinctio pariatur dolores saepe nesciunt.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis,
					numquam quae nostrum ullam voluptatum distinctio maxime eos voluptate
					ea ad quos repudiandae, deserunt non magni magnam pariatur,
					perferendis aut libero incidunt similique aliquam error recusandae
					provident modi. Dolorum, modi. Asperiores vel natus neque accusamus
					iure officia quis amet. Expedita odit maiores debitis explicabo, odio
					est? Ratione necessitatibus laboriosam officia debitis corrupti
					doloremque reprehenderit quisquam quibusdam obcaecati maxime, expedita
					libero facere maiores, magnam alias explicabo quo repudiandae? Quia
					nam maiores recusandae expedita, aperiam fugiat excepturi atque
					commodi inventore fuga officiis, consectetur culpa laboriosam, harum
					mollitia magnam. Distinctio pariatur dolores saepe nesciunt.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis,
					numquam quae nostrum ullam voluptatum distinctio maxime eos voluptate
					ea ad quos repudiandae, deserunt non magni magnam pariatur,
					perferendis aut libero incidunt similique aliquam error recusandae
					provident modi. Dolorum, modi. Asperiores vel natus neque accusamus
					iure officia quis amet. Expedita odit maiores debitis explicabo, odio
					est? Ratione necessitatibus laboriosam officia debitis corrupti
					doloremque reprehenderit quisquam quibusdam obcaecati maxime, expedita
					libero facere maiores, magnam alias explicabo quo repudiandae? Quia
					nam maiores recusandae expedita, aperiam fugiat excepturi atque
					commodi inventore fuga officiis, consectetur culpa laboriosam, harum
					mollitia magnam. Distinctio pariatur dolores saepe nesciunt.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis,
					numquam quae nostrum ullam voluptatum distinctio maxime eos voluptate
					ea ad quos repudiandae, deserunt non magni magnam pariatur,
					perferendis aut libero incidunt similique aliquam error recusandae
					provident modi. Dolorum, modi. Asperiores vel natus neque accusamus
					iure officia quis amet. Expedita odit maiores debitis explicabo, odio
					est? Ratione necessitatibus laboriosam officia debitis corrupti
					doloremque reprehenderit quisquam quibusdam obcaecati maxime, expedita
					libero facere maiores, magnam alias explicabo quo repudiandae? Quia
					nam maiores recusandae expedita, aperiam fugiat excepturi atque
					commodi inventore fuga officiis, consectetur culpa laboriosam, harum
					mollitia magnam. Distinctio pariatur dolores saepe nesciunt.
				</p>
			</main>
		</div>
	);
}
