import Head from "next/head";
import Image from "next/image";
import Artikel from "../components/artikel/Artikel";
import Informasi from "../components/informasi/Informasi";
import Kontak from "../components/kontak/Kontak";
import Layout from "../components/layout/Layout";
import Media from "../components/media/Media";
import Navbar from "../components/navbar/Navbar";
import Profil from "../components/profil/Profil";

import styles from "../styles/Home.module.css";

export default function PageHome() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Paroki Santo Yakobus</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className={styles.header}>
				<Navbar />
			</header>

			<main className={styles.main}>
				<div className={styles.heroWrapper}>
					<Image
						className={styles.heroImage}
						priority
						src={"/static/hero.jpg"}
						alt="Foto Gereja Paroki"
						width={1600}
						height={900}
					/>
					<div className={styles.heroContent}>
						<p className={styles.heroText}>
							<span>PAROKI</span>
							<span>SANTO YAKOBUS</span>
							<span>BANTUL</span>
						</p>
						<div className={styles.heroButtons}>
							<button className={styles.button}>PENGUMUMAN PAROKI</button>
							<button className={styles.button}>JADWAL EKARISTI</button>
						</div>
					</div>
				</div>

				<Profil />
				<Informasi />
				<Artikel />
				<Media />
			</main>

			<footer className={styles.footer}>
				<div className={styles.kontak}>
					<p>Hubungi Kami</p>
					<p>Jl. Mgr Soegijapranata No.1 55171 Bantul</p>
				</div>
			</footer>
		</div>
	);
}
